--DROP TABLE BUDM_UOR.UOR_DET_EMPLOYEE;
CREATE TABLE BUDM_UOR.UOR_DET_EMPLOYEE (
	CODE VARCHAR2(256),
	SURNAME VARCHAR2(256),
	NAME VARCHAR2(256),
	SECOND_NAME VARCHAR2(256),
	CODE_DEPARTMENT VARCHAR2(256),
	ID_DEPARTMENT VARCHAR2(16),
	NAME_DEPARTMENT VARCHAR2(256),
	CODE_POSITION VARCHAR2(256),
	NAME_POSITION VARCHAR2(256),
	IS_MANAGER NUMBER(1),
	DT_FIRE DATE,
	DSC_EMAIL VARCHAR2(256),
	DTTM_INSERT DATE 

										
);

--DROP TABLE BUDM_UOR.UOR_BM_DET_DEPARTMENT;
CREATE TABLE BUDM_UOR.UOR_BM_DET_DEPARTMENT ()
	CODE VARCHAR2(256)
	NAME_DEPARTMENT VARCHAR2(256),
	CODE_ABBRV VARCHAR2(100),
	CODE_PARENT VARCHAR2(100),
	CODE_ASUP_FIL VARCHAR2(100),
	CODE_TYPE_DEPARTMENT VARCHAR2(100),
	CODE_BALANCE VARCHAR2(100),
	DTTM_INSERT DATE 
);

--DROP TABLE BUDM_UOR.UOR_FCT_ASCEVENT;
CREATE TABLE BUDM_UOR.UOR_FCT_ASCEVENT (
	CODE_EMPLOYEE VARCHAR2(256),
	DT DATE,
	TIME DATE,
	CODE_ASCEVENTTYPE VARCHAR2(256),
	DTTM_INSERT DATE 
);

--DROP TABLE BUDM_UOR.UOR_FCT_EMPLOYEEABSCENE;
CREATE TABLE BUDM_UOR.UOR_FCT_EMPLOYEEABSCENE (
	CODE_EMPLOYEE VARCHAR2(256),
    CODE_EMPLOYEEABSCENEKIND VARCHAR2(256),
	IS_BLOCKED NUMBER(16),
    DATE_START_PERIOD DATE,
	DATE_END_PERIOD DATE,
	NAME_EMPLOYEEABSCENEKIND VARCHAR2(256),
	DTTM_INSERT DATE 
);

--DROP TABLE BUDM_UOR.UOR_FCT_STAFFTURNOVER;
CREATE TABLE BUDM_UOR.UOR_FCT_STAFFTURNOVER (
	YEAR NUMBER(16),
	QUARTER NUMBER(16),
	CODE_DEPARTMENT NUMBER(16),
	NAME_DEPARTMENT VARCHAR2(256),
	MANNINGTABLE_START VARCHAR2(256),
	MANNINGTABLE_END NUMBER(16),
	MANNINGTABLE_CHANGE NUMBER(16),
	EMPLOYEES_COUNT_START NUMBER(16),
	EMPLOYEES_COUNT_END NUMBER(16),
	EMPLOYEES_COUNT_CHANGE NUMBER(16),
	HEADCOUNT_START NUMBER(16),
	HEADCOUNT_END NUMBER(16),
	HEADCOUNT_CHANGE NUMBER(16),
	AVG_HEADCOUNT NUMBER(16),
	AVG_HEADCOUNT_MANAGER NUMBER(16),
	AVG_HEADCOUNT_SPECIALIST NUMBER(16),
	VACANCY_START NUMBER(16),
	VACANCY_END NUMBER(16),
	HIRED NUMBER(16),
	HIRED_MANAGER NUMBER(16),
	FIRED NUMBER(16),
	FIRED_MANAGER NUMBER(16),
	TURNOVER NUMBER(16),
	TURNOVER_MANAGER NUMBER(16),
	TURNOVER_SPECIALIST NUMBER(16),
	DTTM_INSERT DATE
);

-- DROP TABLE "BUDM_UOR_TMD"."OR_LOG_TMD";
CREATE TABLE "BUDM_UOR_TMD"."OR_LOG_TMD" 
   ("ID_LOG" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"NAME_PROC" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ROW_COUNT" NUMBER, 
	"X_BEGIN_DATE" DATE, 
	"X_END_DATE" DATE
   );
  
  

