  GRANT SELECT ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "EDM_UOR";
  GRANT SELECT ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "BUDM_UOR_TMD";
  GRANT INSERT ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "BUDM_UOR_TMD";
  GRANT DELETE ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "BUDM_UOR_TMD";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "UOR_ALL_READER";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_ASCEVENT" TO "INTECH";

 
 
GRANT SELECT ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "EDM_UOR";
  GRANT SELECT ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "BUDM_UOR_TMD";
  GRANT INSERT ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "BUDM_UOR_TMD";
  GRANT DELETE ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "BUDM_UOR_TMD";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "UOR_ALL_READER";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_EMPLOYEEABSCENE" TO "INTECH";
 
 
GRANT SELECT ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "EDM_UOR";
  GRANT SELECT ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "BUDM_UOR_TMD";
  GRANT INSERT ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "BUDM_UOR_TMD";
  GRANT DELETE ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "BUDM_UOR_TMD";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "UOR_ALL_READER";
  --GRANT SELECT ON "BUDM_UOR"."UOR_FCT_STAFFTURNOVER" TO "INTECH";
 
 
 
GRANT SELECT ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "EDM_UOR";
  GRANT SELECT ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "BUDM_UOR_TMD";
  GRANT INSERT ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "BUDM_UOR_TMD";
  GRANT DELETE ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "BUDM_UOR_TMD";
  --GRANT SELECT ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "UOR_ALL_READER";
  --GRANT SELECT ON "BUDM_UOR"."UOR_DET_EMPLOYEE" TO "INTECH";
 
 
 GRANT SELECT ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "EDM_UOR";
  GRANT SELECT ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "BUDM_UOR_TMD";
  GRANT INSERT ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "BUDM_UOR_TMD";
  GRANT DELETE ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "BUDM_UOR_TMD";
  --GRANT SELECT ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "UOR_ALL_READER";
  --GRANT SELECT ON BUDM_UOR.UOR_BM_DET_DEPARTMENT TO "INTECH";

